Provide PHP 8.2 compatibility for laminas dependencies
laminas/laminas-di pull request #82
Opened 2022-11-21 06:40 UTC by AshishKumarPundeer

|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### Description

2022-11-21 06:41 UTC, Ocramius commented on .laminas-ci.json
> +    "8.2": true
AFAIK, all dependencies in `composer.json` should be compatible with PHP 8.2, at this stage?

Can you please try dropping this?

2022-11-21 06:41 UTC, Ocramius commented on composer.json
> +        "php": ">=7.4, <=8.2",
Let's kill PHP 7.4, meanwhile.

This becomes: "~8.0.0 || ~8.1.0 || ~8.2.0"`

2022-11-21 06:49 UTC, Ocramius commented
Hmm, we probably need to rewrite the tests that rely on `phpspec/prophecy` to use only PHPUnit mocking

2022-11-21 07:24 UTC, Ocramius commented
@AshishKumarPundeer TODOs:

 1. a run of `vendor/bin/phpcbf`
 2. removal of `ProphecyTrait` from tests

2022-11-21 07:24 UTC, Ocramius commented on phpcs.xml
> +        <exclude name="SlevomatCodingStandard.Classes.ModernClassNameReference.ClassNameReferencedViaFunctionCall"/>
Should be reverted: the CS change is actually needed and valid

2022-11-21 08:35 UTC, AshishKumarPundeer commented
@Ocramius Suggested changes has beed done.

2022-11-21 08:39 UTC, Ocramius commented
@AshishKumarPundeer please look at the CI failures 😁

2022-11-21 10:32 UTC, AshishKumarPundeer commented
Hello @Ocramius 
Our PR is dependent on package **phpspec/prophecy** and they have added the support php 8.2 under this PR https://github.com/phpspec/prophecy/pull/571 which is not yet merged hence it seems once PR will be merged our PR will be green.

Please suggest way forward anything is required our end.

Thanks

2022-11-21 10:35 UTC, Ocramius commented
Hey @AshishKumarPundeer, I already suggested to drop prophecy here, and use PHPUnit mocks instead.

2022-11-21 10:58 UTC, AshishKumarPundeer commented
Hello @Ocramius ,



> Hey @AshishKumarPundeer, I already suggested to drop prophecy here, and use PHPUnit mocks instead.

It may be the silly question for you just for clarification can we use this  phpspec/prophecy-phpunit or phpunit only.

2022-11-21 11:38 UTC, Ocramius commented
Let's please phase out prophecy overall: PHPUnit only 👍

2022-11-21 11:51 UTC, AshishKumarPundeer commented
> Let's please phase out prophecy overall: PHPUnit only 👍

We have already removed ProphecyTrait in tests file,Can you please suggest in which files we need to remove the prophecy now.

2022-11-21 11:53 UTC, Ocramius commented
Effectively, `->prophesize()` calls need to be replaced with `->createMock()` (and associated API) in the test classes :)

2022-11-21 13:18 UTC, AshishKumarPundeer commented
> Effectively, `->prophesize()` calls need to be replaced with `->createMock()` (and associated API) in the test classes :)


we have used createMock() in place of prophesize() but below are some interfaces in which we are facing the issues.
use Laminas\Di\InjectorInterface;
use Psr\Log\LoggerInterface
use Psr\Container\ContainerInterface;

eg. $container = $this->createMock(ContainerInterface::class)->reveal();

we have tried various things but it is not resolved yet please suggest what we should do for this.

Thanks

2022-11-21 13:27 UTC, gsteel commented
> (and associated API)

@AshishKumarPundeer you may find it helpful to read the chapter on [PHPUnit mocks here](https://phpunit.readthedocs.io/en/9.5/test-doubles.html#mock-objects). `reveal()` is part of the Prophecy api. There are some similarities between the mocking api of PHPUnit and prophecy, but you must review each mock individually and ensure that all of the expectations match the current test suite.

2022-11-23 11:13 UTC, samsonasik commented
@AshishKumarPundeer instead of randomly push and wait CI to run test, you can verify locally first and make a commit when all ok:

```
./vendor/bin/phpcs -q --report=checkstyle
./vendor/bin/phpunit
```

2022-11-23 11:30 UTC, samsonasik commented on test/CodeGenerator/InjectorGeneratorTest.php
> +        $logger->debug(Argument::containingString(TestAsset\B::class));
Please read the PHPUnit documentation how to do this https://phpunit.readthedocs.io/en/9.5/test-doubles.html , read slowly, run locally first before to avoid random commit and wait CI to run, that's will make unnecessary noise

2022-11-24 08:26 UTC, glo82145 commented on test/CodeGenerator/InjectorGeneratorTest.php
> +        $logger->debug(Argument::containingString(TestAsset\B::class));
I apologise for some random commits but some test cases are passing on local and not here

2022-11-24 10:07 UTC, glo82145 commented
@Ocramius @samsonasik All testcases are passing now, please review and merge the PR

2022-11-25 08:16 UTC, Ocramius requested changes
Thanks @AshishKumarPundeer

I noted a bunch of feedback on the PR, which I'll apply locally now, while merging :)

2022-11-25 08:16 UTC, Ocramius commented on test/CodeGenerator/AbstractInjectorTest.php
>      private $decoratedInjectorProphecy;
This is no longer a "prophecy": to be renamed

2022-11-25 08:16 UTC, Ocramius commented on test/CodeGenerator/AbstractInjectorTest.php
> +        $prophecy = $this->createMock(InvokableInterface::class);
No longer a prophecy: to be renamed

2022-11-25 08:16 UTC, Ocramius commented on test/CodeGenerator/AbstractInjectorTest.php
> -        $this->assertFalse($subject->canCreate($missingClass));
To be reverted: we expect this call to be `false`

2022-11-25 08:16 UTC, Ocramius commented on test/CodeGenerator/AbstractInjectorTest.php
> -            ->shouldBeCalled()
I think we miss an `->atLeastOnce()` somewhere

2022-11-25 08:16 UTC, Ocramius commented on test/CodeGenerator/AbstractInjectorTest.php
> -            ->shouldBeCalled()
We probably miss an `->atLeastOnce()` here

2022-11-25 08:16 UTC, Ocramius commented on test/CodeGenerator/InjectorGeneratorTest.php
> +            ->expects($this->any())
`self::any()`

2022-11-25 08:16 UTC, Ocramius commented on test/CodeGenerator/InjectorGeneratorTest.php
> +            ->expects($this->any())
`self::any()`

2022-11-25 08:16 UTC, Ocramius commented on test/CodeGenerator/InjectorGeneratorTest.php
> +            ->expects($this->any())
We probably want an `atLeastOnce()` here

2022-11-25 08:16 UTC, Ocramius commented on test/CodeGenerator/InjectorGeneratorTest.php
> +        $this->assertNull($logger->error('Bad.And.Undefined.ClassName'));
This doesn't seem to test anything.

I think the mock assertion needs to be moved up, before the generator is called.

2022-11-25 08:16 UTC, Ocramius commented on test/CodeGenerator/AbstractInjectorTest.php
> +        $this->assertSame($expected, $subject->create($className, $params));
`$params` should probably not be passed here.

2022-11-25 08:16 UTC, Ocramius commented on test/GeneratedInjectorDelegatorTest.php
> +            ->willReturn(true);
We miss a `self::once()` here

2022-11-25 08:16 UTC, Ocramius commented on test/GeneratedInjectorDelegatorTest.php
> +            ->willReturn(['dependencies' => ['auto' => ['aot' => ['namespace' => []]]]]);
We miss a `self::once()` here

2022-11-25 08:16 UTC, Ocramius commented on test/GeneratedInjectorDelegatorTest.php
> +            ->willReturn(false);
We miss a `self::once()` here

2022-11-25 08:16 UTC, Ocramius commented on test/GeneratedInjectorDelegatorTest.php
> +            ->willReturn(true);
We miss a `self::once()` here

2022-11-25 08:16 UTC, Ocramius commented on test/GeneratedInjectorDelegatorTest.php
> +            ->willReturn(['dependencies' => ['auto' => ['aot' => ['namespace' => 'LaminasTest\Di\TestAsset']]]]);
We miss a `self::once()` here

2022-11-25 08:50 UTC, merged